baseURL = 'https://nejox.github.io/'
title = "Hi, I'm Jochen"
theme = "gokarna"
languageCode = "en"
defaultContentLanguage = "en"
enableEmoji = true
enableRobotsTXT = true

# Choose one of emacs, trac or perldoc
pygmentsStyle = "monokai"

[params]
  footer = ""
  description = "AI Student  |  Computer Science  |  Software Engineer"
  avatarURL = "/images/le_me.png"
  AvatarAltText = "avatar"
  avatarSize = "size-l"
  accentColor = "#ffa64d"


  customHeadHTML = """
  <script>
      document.getElementsByClassName("footer")[0].childNodes[2].remove()
  </script>
  """
  
  socialIcons = [
    {name = "linkedin", url = "https://www.linkedin.com/in/jochen-schmidt96/"},
    {name = "github", url = "https://github.com/nejox"},
    {name = "kaggle", url = "https://www.kaggle.com/nejoxx"},
    #{name = "stackoverflow", url = "https://example.com"},
    {name = "instagram", url = "https://www.instagram.com/ne.jox/"},
    {name = "email", url = "mailto:schmidtjochen@gmx.net"}
    

  ]
  metaKeywords = ["blog", "gokarna", "hugo"]

[menu]
  #[[menu.main]]
  #  name = "Home"
  #  pre = "<span data-feather='home'></span>"
  #  url = "/"
  #  weight = 1

  #[[menu.main]]
  #  name = "Posts"
  #  pre = "<span data-feather='book'></span>"
  #  url = "/posts/"
  #  weight = 2

  #[[menu.main]]
  #  name = "Projects"
  #  pre = "<span data-feather='code'></span>"
  #  url = "/projects/"
  #  weight = 3

  #[[menu.main]]
  #  name = "Tags"
  #  pre = "<span data-feather='tag'></span>"
  #  url = "/tags/"
  #  weight = 4

  #[[menu.main]]
  #  identifier = "github"
  #  pre = "<span data-feather='github'></span>"
  #  url = "https://github.com/526avijitgupta/gokarna"
  #  weight = 5

  #[[menu.main]]
  #  identifier = "buymeacoffee"
  #  pre = "<span data-feather='coffee'></span>"
  #  url = "https://www.buymeacoffee.com/avijitgupta"
  #  weight = 6

  #[[menu.main]]
  #  identifier = "rss"
  #  pre = "<span data-feather='rss'></span>"
  #  url = "/index.xml"
  #  weight = 7

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = false