name: Check for broken links

on:
  workflow_run:
    workflows: ["Deploy"]
    types: [completed]

jobs:
  check:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Report broken links
        uses: victoriadrake/link-snitch@master
